### ISSUE TITLE
Is pydentic still working?

### ISSUE THREAD

**Issue by MaKaNu** [nuno-andre/pydentic#1]
I tried to inherit the BaseModel to one of my classes and got already Problems to import the BaseModel. I searched through your commit and the only instance of BaseModel is inside the Documentation.

**Comment by MaKaNu** [comment]
Okay I close this issue I am not sure what the plans are here but it seems a bit fishy, since it uses pyd"A"ntic and so on...

**Comment by nuno-andre** [comment]
As stated in readme, its aim is _to facilitate the use of its extensive collection of validators and formatters in **Pydantic** models_. Thus _Pydantic + Identifiers = Pydentic_.

Pydantic is not installed as a dependency since it's not used by this library.
